### ISSUE TITLE
Breakage on Ember 2.12

### ISSUE THREAD

**Issue by bj-mcduck** [ChrisHonniball/ember-highlight-code#5]
I'm getting the following breakage on upgrading to Ember 2.12, and it seems to be coming from something within this package.

```
Cannot find module '/Users/brandonmckay/Foodee/StarFox/bower_components/ember/ember-template-compiler.js'
Error: Cannot find module '/Users/brandonmckay/Foodee/StarFox/bower_components/ember/ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (/Users/brandonmckay/Foodee/StarFox/node_modules/ember-highlight-code/node_modules/ember-cli-htmlbars/ember-addon-main.js:78:25)
    at Object.toTree (/Users/brandonmckay/Foodee/StarFox/node_modules/ember-highlight-code/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:36)
    at /Users/brandonmckay/Foodee/StarFox/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/brandonmckay/Foodee/StarFox/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/Users/brandonmckay/Foodee/StarFox/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
```

**Comment by ChrisHonniball** [comment]
Updated the plugin to 2.12.1. Please let me know if this fixes the issue.
